
# Font config:
[ font ]
normal = { family = "jetbrainsmono nerd font", style = "Regular"}
bold= { family = "jetbrainsmono nerd font", style = "Bold"}
italic= { family = "jetbrainsmono nerd font", style = "Italic"}
bold_italic= { family = "jetbrainsmono nerd font", style = "Bold Italic"}
size = 16

[window]
padding = {x = 14, y = 14}

[general]
# Theme config:
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]
